[db_credentials_1]
account = "grfxvwc-nz59991"
user = "JArjun0207"
password = "Jarjun123"
warehouse = "COMPUTE_WH"

[db_credentials_2]
account = "grfxvwc-nz59991"
user = "JArjun0207"
password = "Jarjun123"
warehouse = "COMPUTE_WH"
database = "ML_SFDEMO"
schema = "ML_DEMO"

