[db_credentials_1]
account = "fdgujgb-zbb99923"
user = "admteam7"
password = "helloadmteamSeven@1998"
warehouse = "DASH_L"
role = "ACCOUNTADMIN"
database = "DASH_DB"
schema = "DASH_SCHEMA"

[db_credentials_2]
account = "fdgujgb-zbb99923"
user = "admteam7"
password = "helloadmteamSeven@1998"
warehouse = "COMPUTE_WH"
database = "ML_SFDEMO"
schema = "ML_DEMO"

[db_credentials_3]
user='admteam7'
password='helloadmteamSeven@1998'
account='fdgujgb-zbb99923'
warehouse='FE_AND_INFERENCE_WH'
database='tpcds_xgboost'
schema='demo'







